# Generated by Django 5.2.17 on 2026-08-18 18:32

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,8}$', 'Use 2–8 capital letters or digits — this becomes part of the design code.')])),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,8}$', 'Use 2–8 capital letters or digits — this becomes part of the design code.')])),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive seasons stay on old designs but are not offered for new ones.')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('logo_file', models.FileField(blank=True, upload_to='assets/logos/')),
                ('colour_code', models.CharField(blank=True, help_text='Pantone or equivalent, e.g. 19-4324 TCX. Authoritative — not the image.', max_length=60)),
                ('colour_hex', models.CharField(blank=True, help_text='Optional #RRGGBB, for the swatch chip only.', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='designs.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs_created', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='designs.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='designs.guidancecard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMeasurement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value_cm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('design', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.design')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical measurement',
                'verbose_name_plural': 'historical measurements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value_cm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='designs.design')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('progress', 'In progress'), ('attention', 'Needs attention'), ('good', 'Good'), ('stopped', 'Stopped')], default='neutral', help_text='Controls the badge colour only.', max_length=12)),
                ('is_initial', models.BooleanField(default=False, help_text='The status a newly created design starts in. Exactly one status should have this.')),
                ('is_approval', models.BooleanField(default=False, help_text='Reaching this status means the design is approved and requires a version to be marked final.')),
                ('is_terminal', models.BooleanField(default=False, help_text='No further work is expected. Shown separately from the main pipeline.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'ordering': ['order', 'label'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('is_initial',), name='only_one_initial_status')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDesign',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, editable=False, max_length=32)),
                ('name', models.CharField(max_length=140)),
                ('logo_file', models.TextField(blank=True, max_length=100)),
                ('colour_code', models.CharField(blank=True, help_text='Pantone or equivalent, e.g. 19-4324 TCX. Authoritative — not the image.', max_length=60)),
                ('colour_hex', models.CharField(blank=True, help_text='Optional #RRGGBB, for the swatch chip only.', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.season')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.status')),
            ],
            options={
                'verbose_name': 'historical design',
                'verbose_name_plural': 'historical designs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='design',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='designs.status'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('requirement', models.TextField(blank=True, help_text="What this version was meant to change, in the uploader's own words.")),
                ('image_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('thumbnail_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('content_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 of the uploaded bytes. Catches re-uploads.', max_length=64)),
                ('origin', models.CharField(choices=[('manual_upload', 'Manual upload'), ('api_generated', 'API generated')], default='manual_upload', editable=False, max_length=20)),
                ('is_approved', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions_created', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='designs.design')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='designs.version')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('is_self_approval', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='designs.design')),
                ('from_status', models.ForeignKey(blank=True, help_text='Empty on creation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='designs.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='designs.status')),
                ('version', models.ForeignKey(blank=True, help_text='The version marked final, when this transition approved the design.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='designs.version')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVersion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('number', models.PositiveIntegerField(editable=False)),
                ('requirement', models.TextField(blank=True, help_text="What this version was meant to change, in the uploader's own words.")),
                ('image_key', models.CharField(db_index=True, editable=False, max_length=255)),
                ('thumbnail_key', models.CharField(db_index=True, editable=False, max_length=255)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('content_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 of the uploaded bytes. Catches re-uploads.', max_length=64)),
                ('origin', models.CharField(choices=[('manual_upload', 'Manual upload'), ('api_generated', 'API generated')], default='manual_upload', editable=False, max_length=20)),
                ('is_approved', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.design')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.version')),
            ],
            options={
                'verbose_name': 'historical version',
                'verbose_name_plural': 'historical versions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.version')),
            ],
            options={
                'verbose_name': 'historical comment',
                'verbose_name_plural': 'historical comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='designs.version')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='designs.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='designs.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'category'), name='unique_sequence_per_bucket')],
            },
        ),
        migrations.CreateModel(
            name='AllowedTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='designs.status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='designs.status')),
            ],
            options={
                'ordering': ['from_status__order', 'to_status__order'],
                'constraints': [models.UniqueConstraint(fields=('from_status', 'to_status'), name='unique_transition_pair'), models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='transition_changes_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('design', 'number'), name='unique_version_number_per_design'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_approved', True)), fields=('design',), name='one_approved_version_per_design'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='version_is_not_its_own_parent'),
        ),
    ]
