# Generated by Django 5.2.17 on 2026-08-19 03:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_on_card', models.BooleanField(default=False, help_text='Show this field as a chip on the board card. Four or so is the useful maximum.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive fields stay on existing designs but are not offered on new ones.')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('swatch_hex', models.CharField(blank=True, help_text='Optional #RRGGBB, for the colour chip only. Not a Pantone match.', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='designs.specfield')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDesignSpec',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('design', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.design')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.specfield')),
                ('option', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.specoption')),
            ],
            options={
                'verbose_name': 'historical design spec',
                'verbose_name_plural': 'historical design specs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DesignSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='designs.design')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='designs.specfield')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='designs.specoption')),
            ],
            options={
                'ordering': ['field__order', 'field__label'],
            },
        ),
        migrations.AddConstraint(
            model_name='specoption',
            constraint=models.UniqueConstraint(fields=('field', 'label'), name='unique_option_label_per_field'),
        ),
        migrations.AddConstraint(
            model_name='designspec',
            constraint=models.UniqueConstraint(fields=('design', 'field'), name='one_value_per_field_per_design'),
        ),
    ]
