# Generated by Django 5.2.17 on 2026-08-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_seed_spec_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='designs.season', verbose_name='Drop'),
        ),
        migrations.AlterField(
            model_name='historicaldesign',
            name='season',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='designs.season', verbose_name='Drop'),
        ),
    ]
